# Generated by Django 4.0.5 on 2022-06-27 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desafio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prueba',
            old_name='nomre',
            new_name='nombre',
        ),
    ]
